### ISSUE TITLE
About the output image size

### ISSUE THREAD

**Issue by raywzy** [LeviBorodenko/motionblur#1]
Hi~ Very great motion blur effects. Thanks a lot. But I found the output size of image will become smaller. If there is any way to maintain the original image size?

**Comment by LeviBorodenko** [comment]
Hey @raywzy,

I have added the argument "keep_image_dim" to the applyTo method. If you now run
`kernel.applyTo(image, keep_image_dim=True)` then instead of performing "valid" convolution, we will use scipy's "same" convolution which conserves image dimensions.

Hope it helps :)

Best,
Levi

**Comment by raywzy** [comment]
> Hey @raywzy,
> 
> I have added the argument "keep_image_dim" to the applyTo method. If you now run
> `kernel.applyTo(image, keep_image_dim=True)` then instead of performing "valid" convolution, we will use scipy's "same" convolution which conserves image dimensions.
> 
> Hope it helps :)
> 
> Best,
> Levi

Thank you very much :)

**Comment by LeviBorodenko** [comment]
You're welcome!
